
abstract=
ontologyTitle=Entidades deportivas
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=http://example.org/def/dep#
ontologyName=Entidades deportivas
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.1.
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=Yara Costas, Livia Xavier, Daniel Souto. Entidades deportivas. Revision: 0.1..
DOI=
status=Ontology Specification Draft
logo=
description=
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Yara Costas, Livia Xavier, Daniel Souto
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
