
abstract=
ontologyTitle=Ontología Deportes
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://example.org/partidos/
ontologyName=Ontología Deportes
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=1.0.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs=Santiago Pereira Olmeda, Mateo Fraguas Abal, Gonzalo Landeira Rodríguez. Ontología Deportes. Revision: 1.0.0.
DOI=
status=Ontology Specification Draft
logo=
description=Ontología para la gestión de competiciones deportivas, incluyendo partidos, equipos, campos, grupos y jornadas.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Santiago Pereira Olmeda, Mateo Fraguas Abal, Gonzalo Landeira Rodríguez
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
